version = 1
SPDX-PackageName = "Havneafgifter"
SPDX-PackageSupplier = "Magenta ApS <info@magenta.dk>"

[[annotations]]
path = ["havneafgifter/**",
    "log/**",
    "dev-environment/**",
    "docker/**",
    "docker-compose.yml",
    "docker-compose.override.template.yml",
    "SUMMARY",
    "README.md",
    ".gitignore",
    ".gitlab-ci.yml",
    "mypy.ini",
    "requirements.txt",
    ".coveragerc",
    ".pre-commit-config.yaml",
    "dev-idp/**",
    ".eslint/**",
    "package**.json",
    "REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Magenta ApS <info@magenta.dk>"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = "havneafgifter/havneafgifter/static/jquery/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 OpenJS Foundation and jQuery contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "havneafgifter/havneafgifter/static/bootstrap/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2011-2021 The Bootstrap Authors (https://github.com/twbs/bootstrap/graphs/contributors)"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["havneafgifter/havneafgifter/static/font-awesome/webfonts/**.eot", "havneafgifter/havneafgifter/static/font-awesome/webfonts/**.ttf", "havneafgifter/havneafgifter/static/font-awesome/webfonts/**.woff", "havneafgifter/havneafgifter/static/font-awesome/webfonts/**.woff2"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2011-2021 @fontawesome (https://fontawesome.com)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "havneafgifter/havneafgifter/static/font-awesome/css/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2011-2021 @fontawesome (https://fontawesome.com)"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "havneafgifter/havneafgifter/static/font-awesome/webfonts/**.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2011-2021 @fontawesome (https://fontawesome.com)"
SPDX-License-Identifier = "CC-BY-4.0"
