# Generated by Django 5.0.4 on 2024-04-23 11:27

import django.core.validators
import django.db.models.deletion
import havneafgifter.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HarborDuesForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Indberetningsdato')),
                ('nationality', models.CharField(choices=[('DK', 'Danmark')], max_length=2, verbose_name='Skibets nationalitet')),
                ('vessel_name', models.CharField(max_length=255, verbose_name='Skibets navn')),
                ('vessel_imo', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7), django.core.validators.RegexValidator('\\d{7}'), havneafgifter.models.imo_validator], verbose_name='IMO-nummer')),
                ('vessel_owner', models.CharField(max_length=255, verbose_name='Skibets ejer')),
                ('vessel_master', models.CharField(max_length=255, verbose_name='Skibets kaptajn')),
                ('date_of_arrival', models.DateField(verbose_name='Ankomstdato')),
                ('date_of_departure', models.DateField(verbose_name='Afgangsdato')),
                ('gross_tonnage', models.PositiveIntegerField(verbose_name='Bruttotonnage')),
                ('vessel_type', models.CharField(choices=[('FREIGHTER', 'Fragtskib'), ('FISHER', 'Fiskerbåd'), ('PASSENGER', 'Passagerskib'), ('CRUISE', 'Krydstogtskib')], max_length=9, verbose_name='Skibets type')),
                ('harbour_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Beregnet havneafgift')),
            ],
        ),
        migrations.CreateModel(
            name='DisembarkmentSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Landingssted')),
                ('municipality', models.PositiveSmallIntegerField(choices=[(955, 'Kujalleq'), (958, 'Qaasuitsup'), (957, 'Qeqqata'), (956, 'Sermersooq'), (959, 'Qeqertalik'), (960, 'Avannaata'), (961, 'Nordøstgrønlands nationalpark')], verbose_name='Kommune')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Port name')),
            ],
        ),
        migrations.CreateModel(
            name='PortAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Port authority company name')),
                ('email', models.EmailField(max_length=254, verbose_name='Port authority contact email')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Navn')),
                ('email', models.EmailField(max_length=254, verbose_name='Email-adresse')),
            ],
        ),
        migrations.CreateModel(
            name='TaxRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tax per passenger')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='First day of taking effect')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='First day of no longer taking effect')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('start_date'), nulls_first=True)],
            },
        ),
        migrations.CreateModel(
            name='CruiseTaxForm',
            fields=[
                ('harborduesform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='havneafgifter.harborduesform')),
                ('number_of_passengers', models.PositiveIntegerField(default=0, verbose_name='Antal passagerer')),
                ('pax_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Beregnet passagerafgift')),
                ('disembarkment_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Calculated disembarkment tax')),
            ],
            bases=('havneafgifter.harborduesform',),
        ),
        migrations.AddField(
            model_name='harborduesform',
            name='port_of_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='havneafgifter.port', verbose_name='Ankomsthavn'),
        ),
        migrations.AddField(
            model_name='port',
            name='portauthority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='havneafgifter.portauthority'),
        ),
        migrations.AddField(
            model_name='harborduesform',
            name='shipping_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='havneafgifter.shippingagent', verbose_name='Shippingagent'),
        ),
        migrations.CreateModel(
            name='PortTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_type', models.CharField(blank=True, choices=[('FREIGHTER', 'Fragtskib'), ('FISHER', 'Fiskerbåd'), ('PASSENGER', 'Passagerskib'), ('CRUISE', 'Krydstogtskib')], max_length=9, null=True, verbose_name='Skibets type')),
                ('gt_start', models.PositiveIntegerField(verbose_name='Vessel gross tonnage (lower)')),
                ('gt_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vessel gross tonnage (upper)')),
                ('port_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Tax per gross ton')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='havneafgifter.port', verbose_name='Harbour')),
                ('tax_rates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_tax_rates', to='havneafgifter.taxrates')),
            ],
        ),
        migrations.CreateModel(
            name='PassengersByCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(choices=[('AU', 'Australien'), ('AT', 'Østrig'), ('BE', 'Belgien'), ('CA', 'Canada'), ('CN', 'Kina'), ('CZ', 'Tjekkiet'), ('DK', 'Danmark'), ('FI', 'Finland'), ('FR', 'Frankrig'), ('DE', 'Tyskland'), ('UK', 'Storbritannien'), ('GL', 'Grønland'), ('HK', 'Hong Kong'), ('IS', 'Island'), ('ID', 'Indonesien'), ('IT', 'Italien'), ('JP', 'Japan'), ('LU', 'Luxembourg'), ('MY', 'Malaysien'), ('NL', 'Nederlandene'), ('NZ', 'New Zealand'), ('NO', 'Norge'), ('PL', 'Polen'), ('RU', 'Rusland'), ('SG', 'Singapore'), ('KO', 'Sydkorea'), ('ES', 'Spanien'), ('SE', 'Sverige'), ('CH', 'Schweiz'), ('TW', 'Taiwan'), ('US', 'USA'), ('AS', 'Andet asiatisk land'), ('EU', 'Andet europæisk land'), ('OT', 'Andet land')], max_length=2, verbose_name='Nationalitet')),
                ('number_of_passengers', models.PositiveIntegerField(verbose_name='Antal passagerer fra nationaliteten')),
                ('cruise_tax_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers_by_country', to='havneafgifter.cruisetaxform')),
            ],
        ),
        migrations.CreateModel(
            name='Disembarkment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_passengers', models.PositiveIntegerField(verbose_name='Antal passagerer afskibet')),
                ('disembarkment_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='havneafgifter.disembarkmentsite')),
                ('cruise_tax_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='havneafgifter.cruisetaxform')),
            ],
        ),
        migrations.CreateModel(
            name='DisembarkmentTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.PositiveSmallIntegerField(choices=[(955, 'Kujalleq'), (958, 'Qaasuitsup'), (957, 'Qeqqata'), (956, 'Sermersooq'), (959, 'Qeqertalik'), (960, 'Avannaata'), (961, 'Nordøstgrønlands nationalpark')], verbose_name='Kommune')),
                ('disembarkment_tax_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Disembarkment tax rate')),
                ('disembarkment_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disembarkment_tax_rates', to='havneafgifter.disembarkmentsite', verbose_name='Landingssted')),
                ('tax_rates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disembarkment_tax_rates', to='havneafgifter.taxrates')),
            ],
            options={
                'unique_together': {('tax_rates', 'municipality', 'disembarkment_site')},
            },
        ),
    ]
