# Generated by Django 5.0.4 on 2024-04-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ['portauthority__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='portauthority',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='shippingagent',
            options={'ordering': ['name']},
        ),
    ]
