# Generated by Django 5.0.4 on 2024-04-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disembarkmentsite',
            options={'ordering': ['municipality', 'name']},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ['portauthority__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='portauthority',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='shippingagent',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='disembarkmentsite',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Landingssted'),
        ),
    ]
