# Generated by Django 5.0.4 on 2024-04-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disembarkment',
            options={'ordering': ['cruise_tax_form', 'disembarkment_site__municipality', 'disembarkment_site__name']},
        ),
        migrations.AlterModelOptions(
            name='passengersbycountry',
            options={'ordering': ['cruise_tax_form', 'nationality']},
        ),
    ]
