# Generated by Django 5.0.4 on 2024-05-07 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portauthority',
            options={'ordering': ['name'], 'verbose_name_plural': 'Port authorities'},
        ),
    ]
