# Generated by Django 5.0.4 on 2024-05-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0002_alter_portauthority_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harborduesform',
            name='vessel_type',
            field=models.CharField(choices=[('FREIGHTER', 'Freighter'), ('FISHER', 'Foreign fishing ship'), ('PASSENGER', 'Passenger ship'), ('CRUISE', 'Cruise ship'), ('OTHER', 'Other vessel')], max_length=9, verbose_name='Vessel type'),
        ),
        migrations.AlterField(
            model_name='porttaxrate',
            name='vessel_type',
            field=models.CharField(blank=True, choices=[('FREIGHTER', 'Freighter'), ('FISHER', 'Foreign fishing ship'), ('PASSENGER', 'Passenger ship'), ('CRUISE', 'Cruise ship'), ('OTHER', 'Other vessel')], max_length=9, null=True, verbose_name='Vessel type'),
        ),
    ]
