# Generated by Django 5.0.4 on 2024-05-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0002_alter_disembarkment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disembarkmentsite',
            options={'ordering': ['municipality', 'pk']},
        ),
    ]
