# Generated by Django 5.0.4 on 2024-04-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0002_alter_port_options_alter_portauthority_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disembarkmentsite',
            options={'ordering': ['municipality', 'name']},
        ),
    ]
