# Generated by Django 5.0.4 on 2024-04-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0003_alter_disembarkmentsite_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disembarkmentsite',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Landingssted'),
        ),
    ]
