# Generated by Django 5.0.4 on 2024-05-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0003_alter_harborduesform_vessel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porttaxrate',
            name='round_gross_ton_up_to',
            field=models.PositiveIntegerField(default=0, verbose_name='Round GT up to'),
        ),
    ]
