# Generated by Django 5.0.4 on 2024-05-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0004_porttaxrate_round_gross_ton_up_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disembarkmentsite',
            name='municipality',
            field=models.PositiveSmallIntegerField(choices=[(955, 'Kujalleq'), (957, 'Qeqqata'), (956, 'Sermersooq'), (959, 'Qeqertalik'), (960, 'Avannaata'), (961, 'Northeast Greenland National Park')], verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='disembarkmenttaxrate',
            name='municipality',
            field=models.PositiveSmallIntegerField(choices=[(955, 'Kujalleq'), (957, 'Qeqqata'), (956, 'Sermersooq'), (959, 'Qeqertalik'), (960, 'Avannaata'), (961, 'Northeast Greenland National Park')], verbose_name='Municipality'),
        ),
    ]
