# Generated by Django 5.0.4 on 2024-05-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0005_alter_disembarkmentsite_municipality_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='passengersbycountry',
            unique_together={('cruise_tax_form', 'nationality')},
        ),
    ]
