# Generated by Django 5.0.4 on 2024-05-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0005_alter_disembarkmentsite_municipality_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disembarkment',
            unique_together={('cruise_tax_form', 'disembarkment_site')},
        ),
        migrations.AlterUniqueTogether(
            name='passengersbycountry',
            unique_together={('cruise_tax_form', 'nationality')},
        ),
    ]
