# Generated by Django 5.0.4 on 2024-05-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0007_harborduesformlistview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruisetaxform',
            name='number_of_passengers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of passengers'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='datetime_of_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arrival date/time'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='datetime_of_departure',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Departure date/time'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='gross_tonnage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gross tonnage'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='port_of_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='havneafgifter.port', verbose_name='Port of call'),
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('vessel_type', 'CRUISE'), _negated=True), ('port_of_call__isnull', False)), models.Q(('vessel_type', 'CRUISE'), ('port_of_call__isnull', True)), models.Q(('vessel_type', 'CRUISE'), ('port_of_call__isnull', False)), _connector='OR'), name='port_of_call_cannot_be_null_for_non_cruise_ships'),
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('vessel_type', 'CRUISE'), _negated=True), ('gross_tonnage__isnull', False)), models.Q(('vessel_type', 'CRUISE'), ('gross_tonnage__isnull', True)), models.Q(('vessel_type', 'CRUISE'), ('gross_tonnage__isnull', False)), _connector='OR'), name='gross_tonnage_cannot_be_null_for_non_cruise_ships'),
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('vessel_type', 'CRUISE'), _negated=True), ('datetime_of_arrival__isnull', False)), models.Q(('vessel_type', 'CRUISE'), ('datetime_of_arrival__isnull', True)), models.Q(('vessel_type', 'CRUISE'), ('datetime_of_arrival__isnull', False)), _connector='OR'), name='datetime_of_arrival_cannot_be_null_for_non_cruise_ships'),
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('vessel_type', 'CRUISE'), _negated=True), ('datetime_of_departure__isnull', False)), models.Q(('vessel_type', 'CRUISE'), ('datetime_of_departure__isnull', True)), models.Q(('vessel_type', 'CRUISE'), ('datetime_of_departure__isnull', False)), _connector='OR'), name='datetime_of_departure_cannot_be_null_for_non_cruise_ships'),
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('datetime_of_arrival__isnull', False), ('datetime_of_departure__isnull', False)), models.Q(('datetime_of_arrival__isnull', True), ('datetime_of_departure__isnull', True)), _connector='OR'), name='datetime_of_arrival_and_departure_must_both_be_present_or_both_be_null'),
        ),
    ]
