# Generated by Django 5.0.4 on 2024-06-07 11:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0008_alter_cruisetaxform_number_of_passengers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harborduesform',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/storage/pdf'), upload_to='', verbose_name='PDF file'),
        ),
    ]
