# Generated by Django 5.0.4 on 2024-06-17 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0009_harborduesform_pdf'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='harborduesform',
            name='port_of_call_cannot_be_null_for_non_cruise_ships',
        ),
        migrations.RemoveConstraint(
            model_name='harborduesform',
            name='gross_tonnage_cannot_be_null_for_non_cruise_ships',
        ),
        migrations.RemoveConstraint(
            model_name='harborduesform',
            name='datetime_of_arrival_cannot_be_null_for_non_cruise_ships',
        ),
        migrations.RemoveConstraint(
            model_name='harborduesform',
            name='datetime_of_departure_cannot_be_null_for_non_cruise_ships',
        ),
        migrations.RemoveConstraint(
            model_name='harborduesform',
            name='datetime_of_arrival_and_departure_must_both_be_present_or_both_be_null',
        ),
        migrations.AddField(
            model_name='harborduesform',
            name='status',
            field=models.CharField(choices=[('ny', 'ny'), ('kladde', 'kladde'), ('done', 'done')], default='ny', verbose_name='Draft status'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='nationality',
            field=models.CharField(blank=True, choices=[('', '---'), ('AF', 'Afghanistan'), ('AX', 'Åland Islands'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AS', 'American Samoa'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antarctica'), ('AG', 'Antigua and Barbuda'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BS', 'Bahamas'), ('BH', 'Bahrain'), ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Belgium'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BT', 'Bhutan'), ('BO', 'Bolivia'), ('BQ', 'Bonaire, Sint Eustatius and Saba'), ('BA', 'Bosnia and Herzegovina'), ('BW', 'Botswana'), ('BV', 'Bouvet Island'), ('BR', 'Brazil'), ('IO', 'British Indian Ocean Territory'), ('BN', 'Brunei'), ('BG', 'Bulgaria'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CV', 'Cabo Verde'), ('KH', 'Cambodia'), ('CM', 'Cameroon'), ('CA', 'Canada'), ('KY', 'Cayman Islands'), ('CF', 'Central African Republic'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CX', 'Christmas Island'), ('CC', 'Cocos (Keeling) Islands'), ('CO', 'Colombia'), ('KM', 'Comoros'), ('CG', 'Congo'), ('CD', 'Congo (the Democratic Republic of the)'), ('CK', 'Cook Islands'), ('CR', 'Costa Rica'), ('CI', "Côte d'Ivoire"), ('HR', 'Croatia'), ('CU', 'Cuba'), ('CW', 'Curaçao'), ('CY', 'Cyprus'), ('CZ', 'Czechia'), ('DK', 'Denmark'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('SV', 'El Salvador'), ('GQ', 'Equatorial Guinea'), ('ER', 'Eritrea'), ('EE', 'Estonia'), ('SZ', 'Eswatini'), ('ET', 'Ethiopia'), ('FK', 'Falkland Islands (Malvinas)'), ('FO', 'Faroe Islands'), ('FJ', 'Fiji'), ('FI', 'Finland'), ('FR', 'France'), ('GF', 'French Guiana'), ('PF', 'French Polynesia'), ('TF', 'French Southern Territories'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Germany'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GR', 'Greece'), ('GL', 'Greenland'), ('GD', 'Grenada'), ('GP', 'Guadeloupe'), ('GU', 'Guam'), ('GT', 'Guatemala'), ('GG', 'Guernsey'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HT', 'Haiti'), ('HM', 'Heard Island and McDonald Islands'), ('VA', 'Holy See'), ('HN', 'Honduras'), ('HK', 'Hong Kong'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('IE', 'Ireland'), ('IM', 'Isle of Man'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JP', 'Japan'), ('JE', 'Jersey'), ('JO', 'Jordan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KI', 'Kiribati'), ('KW', 'Kuwait'), ('KG', 'Kyrgyzstan'), ('LA', 'Laos'), ('LV', 'Latvia'), ('LB', 'Lebanon'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('LI', 'Liechtenstein'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MO', 'Macao'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('MV', 'Maldives'), ('ML', 'Mali'), ('MT', 'Malta'), ('MH', 'Marshall Islands'), ('MQ', 'Martinique'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('YT', 'Mayotte'), ('MX', 'Mexico'), ('FM', 'Micronesia'), ('MD', 'Moldova'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MS', 'Montserrat'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('MM', 'Myanmar'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NL', 'Netherlands'), ('NC', 'New Caledonia'), ('NZ', 'New Zealand'), ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('NF', 'Norfolk Island'), ('KP', 'North Korea'), ('MK', 'North Macedonia'), ('MP', 'Northern Mariana Islands'), ('NO', 'Norway'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PW', 'Palau'), ('PS', 'Palestine, State of'), ('PA', 'Panama'), ('PG', 'Papua New Guinea'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PN', 'Pitcairn'), ('PL', 'Poland'), ('PT', 'Portugal'), ('PR', 'Puerto Rico'), ('QA', 'Qatar'), ('RE', 'Réunion'), ('RO', 'Romania'), ('RU', 'Russia'), ('RW', 'Rwanda'), ('BL', 'Saint Barthélemy'), ('SH', 'Saint Helena, Ascension and Tristan da Cunha'), ('KN', 'Saint Kitts and Nevis'), ('LC', 'Saint Lucia'), ('MF', 'Saint Martin (French part)'), ('PM', 'Saint Pierre and Miquelon'), ('VC', 'Saint Vincent and the Grenadines'), ('WS', 'Samoa'), ('SM', 'San Marino'), ('ST', 'Sao Tome and Principe'), ('SA', 'Saudi Arabia'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SG', 'Singapore'), ('SX', 'Sint Maarten (Dutch part)'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SB', 'Solomon Islands'), ('SO', 'Somalia'), ('ZA', 'South Africa'), ('GS', 'South Georgia and the South Sandwich Islands'), ('KR', 'South Korea'), ('SS', 'South Sudan'), ('ES', 'Spain'), ('LK', 'Sri Lanka'), ('SD', 'Sudan'), ('SR', 'Suriname'), ('SJ', 'Svalbard and Jan Mayen'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('SY', 'Syria'), ('TW', 'Taiwan'), ('TJ', 'Tajikistan'), ('TZ', 'Tanzania'), ('TH', 'Thailand'), ('TL', 'Timor-Leste'), ('TG', 'Togo'), ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', 'Trinidad and Tobago'), ('TN', 'Tunisia'), ('TR', 'Türkiye'), ('TM', 'Turkmenistan'), ('TC', 'Turks and Caicos Islands'), ('TV', 'Tuvalu'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('AE', 'United Arab Emirates'), ('GB', 'United Kingdom'), ('UM', 'United States Minor Outlying Islands'), ('US', 'United States of America'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('VG', 'Virgin Islands (British)'), ('VI', 'Virgin Islands (U.S.)'), ('WF', 'Wallis and Futuna'), ('EH', 'Western Sahara'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], max_length=2, null=True, verbose_name='Vessel nationality'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='shipping_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='havneafgifter.shippingagent', verbose_name='Shipping agent'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='vessel_master',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vessel captain'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vessel name'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='vessel_owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vessel owner'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='vessel_type',
            field=models.CharField(blank=True, choices=[('FREIGHTER', 'Freighter'), ('FISHER', 'Foreign fishing ship'), ('PASSENGER', 'Passenger ship'), ('CRUISE', 'Cruise ship'), ('OTHER', 'Other vessel')], max_length=9, null=True, verbose_name='Vessel type'),
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(check=models.Q(('status', 'kladde'), ('vessel_type', 'CRUISE'), ('port_of_call__isnull', False), _connector='OR'), name='port_of_call_cannot_be_null_for_non_cruise_ships', violation_error_code='constraint_violated'),
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(check=models.Q(('status', 'kladde'), ('vessel_type', 'CRUISE'), ('gross_tonnage__isnull', False), _connector='OR'), name='gross_tonnage_cannot_be_null_for_non_cruise_ships', violation_error_code='constraint_violated'),
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(check=models.Q(('status', 'kladde'), ('vessel_type', 'CRUISE'), ('datetime_of_arrival__isnull', False), _connector='OR'), name='datetime_of_arrival_cannot_be_null_for_non_cruise_ships', violation_error_code='constraint_violated'),
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(check=models.Q(('status', 'kladde'), ('vessel_type', 'CRUISE'), ('datetime_of_departure__isnull', False), _connector='OR'), name='datetime_of_departure_cannot_be_null_for_non_cruise_ships', violation_error_code='constraint_violated'),
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(check=models.Q(('status', 'kladde'), models.Q(('datetime_of_arrival__isnull', False), ('datetime_of_departure__isnull', False)), models.Q(('datetime_of_arrival__isnull', True), ('datetime_of_departure__isnull', True)), _connector='OR'), name='datetime_of_arrival_and_departure_must_both_be_present_or_both_be_null', violation_error_code='constraint_violated'),
        ),
    ]
