# Generated by Django 5.0.4 on 2024-06-18 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0009_harborduesform_pdf'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='harborduesform',
            name='port_of_call_cannot_be_null_for_non_cruise_ships',
        ),
        migrations.RemoveConstraint(
            model_name='harborduesform',
            name='gross_tonnage_cannot_be_null_for_non_cruise_ships',
        ),
        migrations.RemoveConstraint(
            model_name='harborduesform',
            name='datetime_of_arrival_cannot_be_null_for_non_cruise_ships',
        ),
        migrations.RemoveConstraint(
            model_name='harborduesform',
            name='datetime_of_departure_cannot_be_null_for_non_cruise_ships',
        ),
        migrations.RemoveConstraint(
            model_name='harborduesform',
            name='datetime_of_arrival_and_departure_must_both_be_present_or_both_be_null',
        ),
        migrations.AddField(
            model_name='harborduesform',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('DRAFT', 'Draft'), ('DONE', 'Done')], default='ny', verbose_name='Draft status'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='nationality',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Vessel nationality'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='shipping_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='havneafgifter.shippingagent', verbose_name='Shipping agent'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='vessel_master',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vessel captain'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vessel name'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='vessel_owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vessel owner'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='vessel_type',
            field=models.CharField(blank=True, choices=[('FREIGHTER', 'Freighter'), ('FISHER', 'Foreign fishing ship'), ('PASSENGER', 'Passenger ship'), ('CRUISE', 'Cruise ship'), ('OTHER', 'Other vessel')], max_length=9, null=True, verbose_name='Vessel type'),
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(check=models.Q(('status', 'DRAFT'), ('nationality__isnull', False), _connector='OR'), name='nationality_cannot_be_null_for_non_drafts', violation_error_code='constraint_violated'),
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(check=models.Q(('status', 'DRAFT'), ('vessel_type', 'CRUISE'), ('port_of_call__isnull', False), _connector='OR'), name='port_of_call_cannot_be_null_for_non_cruise_ships', violation_error_code='constraint_violated'),
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(check=models.Q(('status', 'DRAFT'), ('vessel_type', 'CRUISE'), ('gross_tonnage__isnull', False), _connector='OR'), name='gross_tonnage_cannot_be_null_for_non_cruise_ships', violation_error_code='constraint_violated'),
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(check=models.Q(('status', 'DRAFT'), ('vessel_type', 'CRUISE'), ('datetime_of_arrival__isnull', False), _connector='OR'), name='datetime_of_arrival_cannot_be_null_for_non_cruise_ships', violation_error_code='constraint_violated'),
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(check=models.Q(('status', 'DRAFT'), ('vessel_type', 'CRUISE'), ('datetime_of_departure__isnull', False), _connector='OR'), name='datetime_of_departure_cannot_be_null_for_non_cruise_ships', violation_error_code='constraint_violated'),
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(check=models.Q(('status', 'DRAFT'), models.Q(('datetime_of_arrival__isnull', False), ('datetime_of_departure__isnull', False)), models.Q(('datetime_of_arrival__isnull', True), ('datetime_of_departure__isnull', True)), _connector='OR'), name='datetime_of_arrival_and_departure_must_both_be_present_or_both_be_null', violation_error_code='constraint_violated'),
        ),
    ]
