# Generated by Django 5.0.4 on 2024-06-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0010_remove_harborduesform_port_of_call_cannot_be_null_for_non_cruise_ships_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harborduesform',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('DRAFT', 'Draft'), ('DONE', 'Done')], default='NEW', verbose_name='Draft status'),
        ),
    ]
