# Generated by Django 5.0.4 on 2024-07-24 10:36

import csp_helpers.mixins
import django.contrib.auth.mixins
import django_tables2.views
import havneafgifter.view_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0011_alter_harborduesform_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model, csp_helpers.mixins.CSPViewMixin, django_tables2.views.SingleTableMixin, havneafgifter.view_mixins.GetFormView),
        ),
    ]
