# Generated by Django 5.0.4 on 2024-07-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0012_statisticsview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harborduesform',
            name='nationality',
            field=models.CharField(blank=True, choices=[('AU', 'Australia'), ('AT', 'Austria'), ('BE', 'Belgium'), ('CA', 'Canada'), ('CN', 'China'), ('CZ', 'Czech Republic'), ('DK', 'Denmark'), ('FI', 'Finland'), ('FR', 'France'), ('DE', 'Germany'), ('UK', 'United Kingdom'), ('GL', 'Greenland'), ('HK', 'Hong Kong'), ('IS', 'Iceland'), ('ID', 'Indonesia'), ('IT', 'Italy'), ('JP', 'Japan'), ('LU', 'Luxembourg'), ('MY', 'Malaysia'), ('NL', 'Netherlands'), ('NZ', 'New Zealand'), ('NO', 'Norway'), ('PL', 'Poland'), ('RU', 'Russia'), ('SG', 'Singapore'), ('KO', 'South Korea'), ('ES', 'Spain'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('TW', 'Taiwan'), ('US', 'United States of America'), ('AS', 'Other asian country'), ('EU', 'Other European country'), ('OT', 'Other')], max_length=2, null=True, verbose_name='Vessel nationality'),
        ),
    ]
