# Generated by Django 5.0.4 on 2024-08-02 12:50

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0014_alter_harborduesform_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harborduesform',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DONE', 'Done')], default='DRAFT', max_length=50, protected=True, verbose_name='Draft status'),
        ),
    ]
