# Generated by Django 5.0.4 on 2024-08-15 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0015_alter_harborduesform_status_historicalcruisetaxform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='havneafgifter.port'),
        ),
    ]
