# Generated by Django 5.0.4 on 2024-08-14 11:48

import django.contrib.auth.mixins
import django_tables2.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0015_alter_harborduesform_status_historicalcruisetaxform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarborTaxRateListView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model, django_tables2.views.SingleTableView),
        ),
    ]
