# Generated by Django 5.0.4 on 2024-08-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0016_user_port'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HarborDuesFormListView',
        ),
        migrations.DeleteModel(
            name='StatisticsView',
        ),
    ]
