# Generated by Django 5.0.4 on 2024-08-19 15:32

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0017_delete_harborduesformlistview_delete_statisticsview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harborduesform',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('NEW', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DONE', 'Done')], default='DRAFT', max_length=50, protected=True, verbose_name='Draft status'),
        ),
        migrations.AlterField(
            model_name='historicalcruisetaxform',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('NEW', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DONE', 'Done')], default='DRAFT', max_length=50, protected=True, verbose_name='Draft status'),
        ),
        migrations.AlterField(
            model_name='historicalharborduesform',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('NEW', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DONE', 'Done')], default='DRAFT', max_length=50, protected=True, verbose_name='Draft status'),
        ),
    ]
