# Generated by Django 5.0.4 on 2024-08-19 11:20

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0017_delete_harborduesformlistview_delete_statisticsview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harborduesform',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Submission date'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50, protected=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalcruisetaxform',
            name='date',
            field=models.DateField(blank=True, editable=False, verbose_name='Submission date'),
        ),
        migrations.AlterField(
            model_name='historicalcruisetaxform',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50, protected=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalharborduesform',
            name='date',
            field=models.DateField(blank=True, editable=False, verbose_name='Submission date'),
        ),
        migrations.AlterField(
            model_name='historicalharborduesform',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50, protected=True, verbose_name='Status'),
        ),
    ]
