# Generated by Django 5.0.4 on 2024-08-20 07:27

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0018_alter_harborduesform_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harborduesform',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('NEW', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50, protected=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalcruisetaxform',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('NEW', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50, protected=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalharborduesform',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('NEW', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50, protected=True, verbose_name='Status'),
        ),
    ]
