# Generated by Django 5.0.4 on 2024-08-20 13:05

import django.core.validators
import django.db.models.deletion
import havneafgifter.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0019_alter_harborduesform_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('FREIGHTER', 'Freighter'), ('FISHER', 'Foreign fishing ship'), ('PASSENGER', 'Passenger ship'), ('CRUISE', 'Cruise ship'), ('OTHER', 'Other vessel')], max_length=9, null=True, verbose_name='Vessel type')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vessel name')),
                ('imo', models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7), django.core.validators.RegexValidator('\\d{7}'), havneafgifter.models.imo_validator], verbose_name='IMO-number')),
                ('owner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vessel owner')),
                ('master', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vessel captain')),
                ('gross_tonnage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Gross tonnage')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
