# Generated by Django 5.1.3 on 2024-12-16 11:53

import django.core.validators
import django_fsm
import havneafgifter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0021_alter_disembarkment_number_of_passengers_and_more_squashed_0022_alter_port_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harborduesform',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Submitted'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='datetime_of_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arrival'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='datetime_of_departure',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Departure'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('NEW', 'Awaiting'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50, protected=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='harborduesform',
            name='vessel_imo',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7), django.core.validators.RegexValidator('\\d{7}'), havneafgifter.models.imo_validator], verbose_name='IMO-no.'),
        ),
        migrations.AlterField(
            model_name='historicalcruisetaxform',
            name='date',
            field=models.DateField(blank=True, editable=False, verbose_name='Submitted'),
        ),
        migrations.AlterField(
            model_name='historicalcruisetaxform',
            name='datetime_of_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arrival'),
        ),
        migrations.AlterField(
            model_name='historicalcruisetaxform',
            name='datetime_of_departure',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Departure'),
        ),
        migrations.AlterField(
            model_name='historicalcruisetaxform',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('NEW', 'Awaiting'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50, protected=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalcruisetaxform',
            name='vessel_imo',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7), django.core.validators.RegexValidator('\\d{7}'), havneafgifter.models.imo_validator], verbose_name='IMO-no.'),
        ),
        migrations.AlterField(
            model_name='historicalharborduesform',
            name='date',
            field=models.DateField(blank=True, editable=False, verbose_name='Submitted'),
        ),
        migrations.AlterField(
            model_name='historicalharborduesform',
            name='datetime_of_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arrival'),
        ),
        migrations.AlterField(
            model_name='historicalharborduesform',
            name='datetime_of_departure',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Departure'),
        ),
        migrations.AlterField(
            model_name='historicalharborduesform',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('NEW', 'Awaiting'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50, protected=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalharborduesform',
            name='vessel_imo',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7), django.core.validators.RegexValidator('\\d{7}'), havneafgifter.models.imo_validator], verbose_name='IMO-no.'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='imo',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7), django.core.validators.RegexValidator('\\d{7}'), havneafgifter.models.imo_validator], verbose_name='IMO-no.'),
        ),
    ]
