# Generated by Django 5.1.3 on 2025-01-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0023_alter_harborduesform_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrates',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='taxrates',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start date'),
        ),
    ]
