# Generated by Django 5.1.3 on 2025-03-20 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0025_vessel_nationality_alter_harborduesform_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portauthority',
            name='name',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32, message='Navnet er for langt'), django.core.validators.MinLengthValidator(4, message='Navnet er for kort')], verbose_name='Port authority company name'),
        ),
    ]
