# Generated by Django 5.1.3 on 2025-03-21 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0027_disembarkment_disembarkment_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disembarkment',
            name='number_of_passengers',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Tallet er for lille'), django.core.validators.MaxValueValidator(20000, message='Tallet er for stort')], verbose_name='Number of passengers at time of disembarkment'),
        ),
    ]
