# Generated by Django 5.1.3 on 2025-03-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0028_alter_disembarkment_number_of_passengers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='harborduesform',
            name='datetime_of_arrival_cannot_be_null_for_non_cruise_ships',
        ),
        migrations.RemoveConstraint(
            model_name='harborduesform',
            name='datetime_of_arrival_and_departure_must_both_be_present_or_both_be_null',
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), ('datetime_of_arrival__isnull', False), _connector='OR'), name='datetime_of_arrival_cannot_be_null_for_non_drafts', violation_error_code='constraint_violated'),
        ),
        migrations.AddConstraint(
            model_name='harborduesform',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), ('datetime_of_departure__isnull', False), models.Q(('port_of_call__isnull', True), ('datetime_of_departure__isnull', True)), _connector='OR'), name='datetime_of_arrival_and_departure_must_both_be_present_or_departure_and_port_of_call_are_null', violation_error_code='constraint_violated'),
        ),
    ]
