# Generated by Django 5.1.3 on 2025-04-14 09:07

import django.core.validators
import havneafgifter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0029_alter_harborduesform_vessel_imo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harborduesform',
            name='vessel_imo',
            field=models.CharField(blank=True, null=True, verbose_name='IMO-no.'),
        ),
        migrations.AlterField(
            model_name='historicalcruisetaxform',
            name='vessel_imo',
            field=models.CharField(blank=True, null=True, verbose_name='IMO-no.'),
        ),
        migrations.AlterField(
            model_name='historicalharborduesform',
            name='vessel_imo',
            field=models.CharField(blank=True, null=True, verbose_name='IMO-no.'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='imo',
            field=models.CharField(unique=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7), django.core.validators.RegexValidator('\\d{7}'), havneafgifter.models.imo_validator], verbose_name='IMO-no.'),
        ),
    ]
