# Generated by Django 5.1.3 on 2025-04-01 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0029_alter_harborduesform_vessel_imo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='imo',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(7)], verbose_name='IMO-no.'),
        ),
    ]
