# Generated by Django 5.1.3 on 2025-04-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0030_alter_harborduesform_vessel_imo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='imo',
            field=models.CharField(unique=True, verbose_name='IMO-no. or nickname'),
        ),
    ]
