# Generated by Django 5.1.3 on 2025-04-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0031_alter_vessel_imo'),
    ]

    operations = [
        migrations.AddField(
            model_name='harborduesform',
            name='no_port_of_call',
            field=models.BooleanField(default=False, verbose_name='No port of call'),
        ),
        migrations.AddField(
            model_name='historicalcruisetaxform',
            name='no_port_of_call',
            field=models.BooleanField(default=False, verbose_name='No port of call'),
        ),
        migrations.AddField(
            model_name='historicalharborduesform',
            name='no_port_of_call',
            field=models.BooleanField(default=False, verbose_name='No port of call'),
        ),
    ]
