# Generated by Django 5.1.3 on 2025-05-27 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0032_harborduesform_no_port_of_call_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portauthority',
            name='admin_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Port authority admin user'),
        ),
    ]
