# Generated by Django 5.1.3 on 2025-06-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0033_portauthority_admin_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disembarkment',
            unique_together=set(),
        ),
    ]
