# Generated by Django 5.1.3 on 2025-06-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0034_alter_disembarkment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruisetaxform',
            name='number_of_passengers',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Number of passengers'),
        ),
        migrations.AlterField(
            model_name='historicalcruisetaxform',
            name='number_of_passengers',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Number of passengers'),
        ),
    ]
