# Generated by Django 5.1.3 on 2025-06-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0035_alter_cruisetaxform_number_of_passengers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruisetaxform',
            name='number_of_passengers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of passengers'),
        ),
        migrations.AlterField(
            model_name='historicalcruisetaxform',
            name='number_of_passengers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of passengers'),
        ),
    ]
