# Generated by Django 5.1.3 on 2025-07-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0036_alter_cruisetaxform_number_of_passengers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harborduesform',
            name='agent_reference',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Agent reference'),
        ),
        migrations.AddField(
            model_name='historicalcruisetaxform',
            name='agent_reference',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Agent reference'),
        ),
        migrations.AddField(
            model_name='historicalharborduesform',
            name='agent_reference',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Agent reference'),
        ),
    ]
