# Generated by Django 5.2.6 on 2026-01-15 14:47

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0037_harborduesform_agent_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harborduesform',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('NEW', 'Awaiting'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INVOICED', 'Invoiced')], default='DRAFT', max_length=50, protected=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalcruisetaxform',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('NEW', 'Awaiting'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INVOICED', 'Invoiced')], default='DRAFT', max_length=50, protected=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalharborduesform',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('NEW', 'Awaiting'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INVOICED', 'Invoiced')], default='DRAFT', max_length=50, protected=True, verbose_name='Status'),
        ),
    ]
