# Generated by Django 5.2.6 on 2026-01-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0037_harborduesform_agent_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harborduesform',
            name='vessel_type',
            field=models.CharField(blank=True, choices=[('CRUISE', 'Cruise ship'), ('FREIGHTER', 'Freighter'), ('FISHER', 'Foreign fishing ship'), ('PASSENGER', 'Passenger ship'), ('OTHER', 'Other vessel')], max_length=9, null=True, verbose_name='Vessel type'),
        ),
        migrations.AlterField(
            model_name='historicalcruisetaxform',
            name='vessel_type',
            field=models.CharField(blank=True, choices=[('CRUISE', 'Cruise ship'), ('FREIGHTER', 'Freighter'), ('FISHER', 'Foreign fishing ship'), ('PASSENGER', 'Passenger ship'), ('OTHER', 'Other vessel')], max_length=9, null=True, verbose_name='Vessel type'),
        ),
        migrations.AlterField(
            model_name='historicalharborduesform',
            name='vessel_type',
            field=models.CharField(blank=True, choices=[('CRUISE', 'Cruise ship'), ('FREIGHTER', 'Freighter'), ('FISHER', 'Foreign fishing ship'), ('PASSENGER', 'Passenger ship'), ('OTHER', 'Other vessel')], max_length=9, null=True, verbose_name='Vessel type'),
        ),
        migrations.AlterField(
            model_name='porttaxrate',
            name='vessel_type',
            field=models.CharField(blank=True, choices=[('CRUISE', 'Cruise ship'), ('FREIGHTER', 'Freighter'), ('FISHER', 'Foreign fishing ship'), ('PASSENGER', 'Passenger ship'), ('OTHER', 'Other vessel')], max_length=9, null=True, verbose_name='Vessel type'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='type',
            field=models.CharField(blank=True, choices=[('CRUISE', 'Cruise ship'), ('FREIGHTER', 'Freighter'), ('FISHER', 'Foreign fishing ship'), ('PASSENGER', 'Passenger ship'), ('OTHER', 'Other vessel')], max_length=9, null=True, verbose_name='Vessel type'),
        ),
    ]
