# Generated by Django 5.2.10 on 2026-03-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0038_alter_harborduesform_vessel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disembarkmentsite',
            name='prisme_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='prisme_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
