# Generated by Django 5.2.12 on 2026-03-27 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0039_disembarkmentsite_prisme_code_port_prisme_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingagent',
            name='cvr',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
