# Generated by Django 5.2.12 on 2026-03-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0040_shippingagent_cvr'),
    ]

    operations = [
        migrations.AddField(
            model_name='harborduesform',
            name='prisme_recid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcruisetaxform',
            name='prisme_recid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalharborduesform',
            name='prisme_recid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
