# Generated by Django 5.2.13 on 2026-04-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0041_harborduesform_prisme_recid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ean',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gln',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
