# Generated by Django 5.2.16 on 2026-08-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havneafgifter', '0044_alter_harborduesform_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harborduesform',
            name='prisme_rec_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcruisetaxform',
            name='prisme_rec_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalharborduesform',
            name='prisme_rec_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
