"""
Django settings for havneafgifter project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import json
import os
import sys
from pathlib import Path

from project.util import strtobool

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
VERSION = os.environ["COMMIT_TAG"]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(strtobool(os.environ.get("DJANGO_DEBUG", "False")))
ENVIRONMENT = os.environ.get("ENVIRONMENT", "development")
TESTING = len(sys.argv) > 1 and sys.argv[1] == "test"

HOST_DOMAIN = os.environ.get("HOST_DOMAIN", "http://talippoq.aka.gl")
ALLOWED_HOSTS = json.loads(os.environ.get("ALLOWED_HOSTS", "[]"))

ROOT_URLCONF = "project.urls"
WSGI_APPLICATION = "project.wsgi.application"

# Uploaded files
MEDIA_ROOT = "/upload/"
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024

# Storage
STORAGE_ROOT = "/storage/"
STORAGE_PDF = os.path.join(STORAGE_ROOT, "pdf")

APPROVER_NO_PORT_OF_CALL = os.environ.get(
    "APPROVER_NO_PORT_OF_CALL", "Royal Arctic Line A/S"
)

if os.environ.get("HOST_DOMAIN", False):
    CSRF_TRUSTED_ORIGINS = [os.environ["HOST_DOMAIN"]]
